sonar.projectKey=conradocmatheus_contact-manager-front
sonar.organization=conradocmatheus
sonar.projectName=Contact Manager Frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,**/node_modules/**,dist/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/contact-manager-front/lcov.info
sonar.qualitygate.wait=true
sonar.sourceEncoding=UTF-8
